LIBRARY IEEE; 
USE IEEE.STD_LOGIC_1164.ALL; 
USE IEEE.NUMERIC_STD.ALL; 

ENTITY GEN_FREC IS  
PORT  
( 
  CLK    : IN STD_LOGIC; 
  F_BASE : IN INTEGER; 
  FREC_OUT : OUT STD_LOGIC 
); 
END GEN_FREC; 

ARCHITECTURE BEHAVIORAL OF GEN_FREC IS 

SIGNAL COUNT1  : INTEGER := 0; 

BEGIN 

PROCESS (CLK) 
BEGIN 
  IF rising_edge(CLK) THEN 
    IF COUNT1 >= F_BASE THEN 
      COUNT1 <= 0; 
      FREC_OUT <= '1'; 
    ELSE 
      COUNT1 <= COUNT1 + 1; 
      FREC_OUT <= '0'; 
    END IF;
  END IF; 
END PROCESS; 

END BEHAVIORAL;
